site_name: StarkBank Payment Orchestrator - Docs
site_description: Documentação técnica da solução de automação de faturamento e repasse.
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Quality & Testing: testing.md
  - Arquitetura:
      - Visão Geral: architecture.md
      - Decisões de Arquitetura (ADRs): architecture_decisions.md
  - Observabilidade:
      - Visão Geral: observability.md
  - API Reference: api.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
