name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: pip

      - name: Cache MkDocs build
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ hashFiles('requirements.txt', 'mkdocs.yml') }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs-material
          # se tiver requirements.txt, use: pip install -r requirements.txt

      - name: Build & Deploy to GitHub Pages
        run: mkdocs gh-deploy --force --clean --verbose